---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  # namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
        - name: backstage
          image: duncandoyle/backstage-gloo:1.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 7007
          env:
          - name: "PORTAL_SERVER_URL"
            value: "{{ .Values.portal_server.url }}"
          - name: "TOKEN_ENDPOINT"
            value: "{{ .Values.oauth.token_endpoint }}"
          - name: "AUTH_ENDPOINT"
            value: "{{ .Values.oauth.auth_endpoint }}"
          - name: "LOGOUT_ENDPOINT"
            value: "{{ .Values.oauth.logout_endpoint }}"
          - name: "CLIENT_ID"
            value: "{{ .Values.oauth.client_id }}"
          - name: "LOG_LEVEL"
            value: "debug"
          envFrom:
            - secretRef:
                name: postgres-secrets
            # - secretRef:
            #     name: backstage-secrets
            # # - secretRef:
            #     name: oauth
            
# Uncomment if health checks are enabled in your app:
# https://backstage.io/docs/plugins/observability#health-checks
#          readinessProbe:
#            httpGet:
#              port: 7007
#              path: /healthcheck
#          livenessProbe:
#            httpGet:
#              port: 7007
#              path: /healthcheck