---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
        - name: backstage
          image: backstage:1.27
          # image: backstage:1.0.2-local
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 7007
          env:
          - name: "PORTAL_SERVER_URL"
            value: "http://developer.example.com/v1/"
          - name: "TOKEN_ENDPOINT"
            # value: "http://keycloak.keycloak.svc.cluster.local/realms/master/protocol/openid-connect/token"
            value: "http://keycloak.example.com/realms/master/protocol/openid-connect/token"
          - name: "AUTH_ENDPOINT"
            # value: "http://keycloak.keycloak.svc.cluster.local/realms/master/protocol/openid-connect/auth"
            value: "http://keycloak.example.com/realms/master/protocol/openid-connect/auth"
          - name: "LOGOUT_ENDPOINT"
            # value: "http://keycloak.keycloak.svc.cluster.local/realms/master/protocol/openid-connect/logout"
            value: "http://keycloak.example.com/realms/master/protocol/openid-connect/logout"
          - name: "CLIENT_ID"
            value: "portal-client"
          - name: "LOG_LEVEL"
            value: "debug"
          envFrom:
            - secretRef:
                name: postgres-secrets
            # - secretRef:
            #     name: backstage-secrets
            # # - secretRef:
            #     name: oauth
            
# Uncomment if health checks are enabled in your app:
# https://backstage.io/docs/plugins/observability#health-checks
#          readinessProbe:
#            httpGet:
#              port: 7007
#              path: /healthcheck
#          livenessProbe:
#            httpGet:
#              port: 7007
#              path: /healthcheck