---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: backstage
type: Opaque
data:
  # backstage
  POSTGRES_USER: YmFja3N0YWdl
  # hunter2, LOL
  POSTGRES_PASSWORD: aHVudGVyMg==